--Po utworzeniu bazy w pliku db/rozgrywki.script ustaw parametr WRITE DELAY na zero tj. SET FILES WRITE DELAY 0 MILLIS
	CREATE TABLE rozgrywka(
	 rozgrywka_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	 gracz_o VARCHAR(32),
	 gracz_x VARCHAR(32),
	 zwyciezca VARCHAR(1),
	 dataczas_rozgrywki TIMESTAMP NOT NULL
	);